-- All migrations in order (generated by npm run docs:schema). Safe to run more than once.

-- ===================== 0001_baseline.sql =====================
-- 0001_baseline.sql
-- Creates every table, the is_admin() helper and all Row Level Security policies.
-- SAFE TO RE-RUN: tables use "if not exists"; policies are dropped and re-created.
-- On a database that already has these tables, this only (re)applies the latest policies.
-- Columns that were added after the first release are handled in 0002_schema_alignment.sql.

-- FGCK Christ Centre, Supabase schema
-- Run in the Supabase SQL editor. Adjust as the CMS grows.

create extension if not exists "uuid-ossp";

-- ============ CORE ============

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'admin' check (role in ('admin','editor')),
  created_at timestamptz not null default now()
);

create table if not exists site_settings (
  id int primary key default 1,
  church_name text not null default 'FGCK Christ Centre',
  tagline text,
  logo_url text,
  favicon_url text,
  hero_image_url text,
  hero_text text,
  about_content text,
  pastor_message text,
  address text,
  phone text,
  email text,
  service_summary text,
  footer_content text,
  hero_title text,
  about_intro text,
  about_history text,
  vision text,
  mission text,
  core_values text,
  beliefs text,
  facebook_url text,
  youtube_url text,
  instagram_url text,
  twitter_url text,
  tiktok_url text,
  whatsapp_number text,
  map_url text,
  map_embed_url text,
  office_hours text,
  seo_title text,
  seo_keywords text,
  seo_description text,
  og_image text,
  show_about boolean not null default true,
  show_leadership boolean not null default true,
  show_departments boolean not null default true,
  show_sermons boolean not null default true,
  show_events boolean not null default true,
  show_cta boolean not null default true,
  -- Theme colors, editable from Admin > Site Settings, applied live via
  -- CSS custom properties (see src/context/ThemeContext.jsx).
  primary_color text not null default '#C62828',
  primary_color_dark text not null default '#8E1C1C',
  primary_color_light text not null default '#E2574A',
  secondary_color text not null default '#E86A1C',
  accent_color text not null default '#EFA80A',
  accent_color_dark text not null default '#B87F06',
  accent_color_light text not null default '#F7CB63',
  navy_color text not null default '#0B1F3A',
  navy_color_light text not null default '#15335C',
  background_color text not null default '#FFFFFF',
  updated_at timestamptz not null default now(),
  constraint single_row check (id = 1)
);
insert into site_settings (id, church_name) values (1, 'FGCK Christ Centre')
  on conflict (id) do nothing;

create table if not exists navigation_items (
  id uuid primary key default uuid_generate_v4(),
  label text not null,
  path text not null,
  display_order int not null default 0,
  published boolean not null default true
);

create table if not exists homepage_sections (
  id uuid primary key default uuid_generate_v4(),
  section_key text not null unique,
  title text,
  content text,
  enabled boolean not null default true,
  display_order int not null default 0
);

-- ============ LEADERSHIP ============

create table if not exists leaders (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  position text not null,
  department text,
  bio text,
  image_url text,
  facebook_url text,
  instagram_url text,
  "order" int not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

-- ============ DEPARTMENTS ============

create table if not exists departments (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  slug text unique,
  description text,
  image_url text,
  leader_id uuid references leaders(id) on delete set null,
  meeting_day text,
  meeting_time text,
  contact_email text,
  contact_phone text,
  display_order int not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists department_members (
  id uuid primary key default uuid_generate_v4(),
  department_id uuid references departments(id) on delete cascade,
  full_name text not null,
  role text,
  created_at timestamptz not null default now()
);

-- ============ MINI CHURCHES ============

create table if not exists mini_churches (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  location text not null,
  leader_name text,
  contact_phone text,
  meeting text,
  members_count int,
  description text,
  image_url text,
  display_order int not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

-- ============ SERVICE SECTORS ============

create table if not exists service_sectors (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  description text,
  coordinator_name text,
  contact_phone text,
  meeting text,
  display_order int not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

-- ============ GALLERY ============

create table if not exists gallery_albums (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  category text,
  cover_image text,
  display_order int not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists gallery_images (
  id uuid primary key default uuid_generate_v4(),
  album_id uuid references gallery_albums(id) on delete cascade,
  image_url text not null,
  title text,
  description text,
  featured boolean not null default false,
  display_order int not null default 0,
  created_at timestamptz not null default now()
);

-- ============ SERMONS ============

create table if not exists sermons (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  speaker text,
  date date not null default current_date,
  scripture text,
  description text,
  thumbnail_url text,
  video_url text,
  audio_url text,
  youtube_url text,
  category text,
  tags text[],
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

-- ============ EVENTS ============

create table if not exists events (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  description text,
  image_url text,
  start_date date not null,
  end_date date,
  start_time time,
  location text,
  organizer text,
  registration_link text,
  contact_info text,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

-- ============ BLOG ============

create table if not exists blog_categories (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  slug text unique not null,
  description text,
  image_url text,
  published boolean not null default true
);

create table if not exists blog_posts (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  slug text unique not null,
  excerpt text,
  content text,
  cover_image text,
  author text,
  author_id uuid references profiles(id),
  category text,
  category_id uuid references blog_categories(id),
  status text not null default 'draft' check (status in ('draft','published','scheduled','archived')),
  seo_title text,
  seo_description text,
  focus_keyword text,
  canonical_url text,
  og_title text,
  og_description text,
  og_image text,
  reading_time int,
  published_at timestamptz,
  scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists blog_tags (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique,
  slug text not null unique
);

create table if not exists blog_post_tags (
  post_id uuid references blog_posts(id) on delete cascade,
  tag_id uuid references blog_tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

-- ============ LIVE SERVICE ============

create table if not exists live_service_settings (
  id int primary key default 1,
  title text not null default 'Sunday Worship Service',
  thumbnail_url text,
  streaming_url text,
  youtube_url text,
  facebook_url text,
  description text,
  day_of_week int not null default 0 check (day_of_week between 0 and 6),
  start_time time not null default '10:00',
  end_time time not null default '12:30',
  timezone text not null default 'Africa/Nairobi',
  status text not null default 'scheduled' check (status in ('scheduled','live','ended')),
  constraint single_row check (id = 1)
);
insert into live_service_settings (id) values (1) on conflict (id) do nothing;

-- ============ COMMUNICATION ============

create table if not exists prayer_requests (
  id uuid primary key default uuid_generate_v4(),
  name text,
  email text,
  phone text,
  message text not null,
  anonymous boolean not null default false,
  status text not null default 'new' check (status in ('new','read','prayed_for','archived')),
  created_at timestamptz not null default now()
);

create table if not exists contact_messages (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  email text not null,
  message text not null,
  status text not null default 'unread' check (status in ('unread','read','archived')),
  created_at timestamptz not null default now()
);

-- ============ GIVING ============

create table if not exists giving_settings (
  id int primary key default 1,
  message text,
  bank_details text,
  mobile_money_details text,
  instructions text,
  mpesa_paybill text,
  mpesa_account text,
  mpesa_till text,
  bank_name text,
  bank_account_name text,
  bank_account_number text,
  bank_branch text,
  constraint single_row check (id = 1)
);
insert into giving_settings (id) values (1) on conflict (id) do nothing;

-- ============ MEDIA ============

create table if not exists media (
  id uuid primary key default uuid_generate_v4(),
  file_url text not null,
  file_type text,
  file_name text,
  file_size int,
  uploaded_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

-- ============ ROW LEVEL SECURITY ============
-- Public (anon) role: read-only, published content only.
-- Authenticated admins (rows in `profiles`): full read/write.

alter table site_settings enable row level security;
alter table navigation_items enable row level security;
alter table homepage_sections enable row level security;
alter table leaders enable row level security;
alter table departments enable row level security;
alter table department_members enable row level security;
alter table mini_churches enable row level security;
alter table service_sectors enable row level security;
alter table gallery_albums enable row level security;
alter table gallery_images enable row level security;
alter table sermons enable row level security;
alter table events enable row level security;
alter table blog_categories enable row level security;
alter table blog_posts enable row level security;
alter table blog_tags enable row level security;
alter table blog_post_tags enable row level security;
alter table live_service_settings enable row level security;
alter table prayer_requests enable row level security;
alter table contact_messages enable row level security;
alter table giving_settings enable row level security;
alter table media enable row level security;
alter table profiles enable row level security;

-- Helper: is the current user an admin?
create or replace function is_admin() returns boolean as $$
  select exists (select 1 from profiles where id = auth.uid());
$$ language sql stable security definer;

-- Public read access to published content
drop policy if exists "public read published leaders" on leaders;
create policy "public read published leaders" on leaders for select using (published = true or is_admin());
drop policy if exists "public read published departments" on departments;
create policy "public read published departments" on departments for select using (published = true or is_admin());
drop policy if exists "public read published mini_churches" on mini_churches;
create policy "public read published mini_churches" on mini_churches for select using (published = true or is_admin());
drop policy if exists "public read published service_sectors" on service_sectors;
create policy "public read published service_sectors" on service_sectors for select using (published = true or is_admin());
drop policy if exists "public read published gallery_albums" on gallery_albums;
create policy "public read published gallery_albums" on gallery_albums for select using (published = true or is_admin());
drop policy if exists "public read gallery_images" on gallery_images;
create policy "public read gallery_images" on gallery_images for select using (true);
drop policy if exists "public read published sermons" on sermons;
create policy "public read published sermons" on sermons for select using (published = true or is_admin());
drop policy if exists "public read published events" on events;
create policy "public read published events" on events for select using (published = true or is_admin());
drop policy if exists "public read published blog_categories" on blog_categories;
create policy "public read published blog_categories" on blog_categories for select using (published = true or is_admin());
drop policy if exists "public read published blog_posts" on blog_posts;
create policy "public read published blog_posts" on blog_posts for select using (status = 'published' or is_admin());
drop policy if exists "public read blog_tags" on blog_tags;
create policy "public read blog_tags" on blog_tags for select using (true);
drop policy if exists "public read blog_post_tags" on blog_post_tags;
create policy "public read blog_post_tags" on blog_post_tags for select using (true);
drop policy if exists "public read site_settings" on site_settings;
create policy "public read site_settings" on site_settings for select using (true);
drop policy if exists "public read navigation_items" on navigation_items;
create policy "public read navigation_items" on navigation_items for select using (published = true or is_admin());
drop policy if exists "public read homepage_sections" on homepage_sections;
create policy "public read homepage_sections" on homepage_sections for select using (enabled = true or is_admin());
drop policy if exists "public read live_service_settings" on live_service_settings;
create policy "public read live_service_settings" on live_service_settings for select using (true);
drop policy if exists "public read giving_settings" on giving_settings;
create policy "public read giving_settings" on giving_settings for select using (true);

-- Anyone can submit prayer requests / contact messages, but only admins can read/manage them
drop policy if exists "anyone can submit prayer requests" on prayer_requests;
create policy "anyone can submit prayer requests" on prayer_requests for insert with check (true);
drop policy if exists "admins manage prayer requests" on prayer_requests;
create policy "admins manage prayer requests" on prayer_requests for select using (is_admin());
drop policy if exists "admins update prayer requests" on prayer_requests;
create policy "admins update prayer requests" on prayer_requests for update using (is_admin());
drop policy if exists "admins delete prayer requests" on prayer_requests;
create policy "admins delete prayer requests" on prayer_requests for delete using (is_admin());

drop policy if exists "anyone can submit contact messages" on contact_messages;
create policy "anyone can submit contact messages" on contact_messages for insert with check (true);
drop policy if exists "admins manage contact messages" on contact_messages;
create policy "admins manage contact messages" on contact_messages for select using (is_admin());
drop policy if exists "admins update contact messages" on contact_messages;
create policy "admins update contact messages" on contact_messages for update using (is_admin());
drop policy if exists "admins delete contact messages" on contact_messages;
create policy "admins delete contact messages" on contact_messages for delete using (is_admin());

-- Admin-only write access everywhere else
drop policy if exists "admins manage leaders" on leaders;
create policy "admins manage leaders" on leaders for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage departments" on departments;
create policy "admins manage departments" on departments for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage department_members" on department_members;
create policy "admins manage department_members" on department_members for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage mini_churches" on mini_churches;
create policy "admins manage mini_churches" on mini_churches for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage service_sectors" on service_sectors;
create policy "admins manage service_sectors" on service_sectors for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage gallery_albums" on gallery_albums;
create policy "admins manage gallery_albums" on gallery_albums for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage gallery_images" on gallery_images;
create policy "admins manage gallery_images" on gallery_images for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage sermons" on sermons;
create policy "admins manage sermons" on sermons for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage events" on events;
create policy "admins manage events" on events for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage blog_categories" on blog_categories;
create policy "admins manage blog_categories" on blog_categories for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage blog_posts" on blog_posts;
create policy "admins manage blog_posts" on blog_posts for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage blog_tags" on blog_tags;
create policy "admins manage blog_tags" on blog_tags for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage blog_post_tags" on blog_post_tags;
create policy "admins manage blog_post_tags" on blog_post_tags for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage site_settings" on site_settings;
create policy "admins manage site_settings" on site_settings for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage navigation_items" on navigation_items;
create policy "admins manage navigation_items" on navigation_items for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage homepage_sections" on homepage_sections;
create policy "admins manage homepage_sections" on homepage_sections for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage live_service_settings" on live_service_settings;
create policy "admins manage live_service_settings" on live_service_settings for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage giving_settings" on giving_settings;
create policy "admins manage giving_settings" on giving_settings for all using (is_admin()) with check (is_admin());
drop policy if exists "admins manage media" on media;
create policy "admins manage media" on media for all using (is_admin()) with check (is_admin());
drop policy if exists "admins read profiles" on profiles;
create policy "admins read profiles" on profiles for select using (is_admin());
drop policy if exists "admins manage profiles" on profiles;
create policy "admins manage profiles" on profiles for all using (is_admin()) with check (is_admin());



notify pgrst, 'reload schema';


-- ===================== 0002_schema_alignment.sql =====================
-- 0002_schema_alignment.sql
-- Repairs "column ... not found in the schema cache" errors.
-- Cause: the live database was created from an earlier version of the schema, and columns that the
-- admin dashboard now reads and writes were added to the code later. "create table if not exists"
-- never adds columns to a table that already exists, so they have to be added explicitly.
-- SAFE TO RE-RUN. Adds columns only; never drops or rewrites data.

-- ---------- site_settings ----------
alter table public.site_settings
  add column if not exists hero_title text,
  add column if not exists hero_image_url text,
  add column if not exists hero_text text,
  add column if not exists about_content text,
  add column if not exists pastor_message text,
  add column if not exists footer_content text,
  add column if not exists about_intro text,
  add column if not exists about_history text,
  add column if not exists vision text,
  add column if not exists mission text,
  add column if not exists core_values text,
  add column if not exists beliefs text,
  add column if not exists facebook_url text,
  add column if not exists youtube_url text,
  add column if not exists instagram_url text,
  add column if not exists twitter_url text,
  add column if not exists tiktok_url text,
  add column if not exists whatsapp_number text,
  add column if not exists map_url text,
  add column if not exists map_embed_url text,
  add column if not exists office_hours text,
  add column if not exists seo_title text,
  add column if not exists seo_keywords text,
  add column if not exists seo_description text,
  add column if not exists og_image text,
  add column if not exists show_about boolean not null default true,
  add column if not exists show_leadership boolean not null default true,
  add column if not exists show_departments boolean not null default true,
  add column if not exists show_sermons boolean not null default true,
  add column if not exists show_events boolean not null default true,
  add column if not exists show_cta boolean not null default true,
  add column if not exists primary_color text not null default '#C62828',
  add column if not exists primary_color_dark text not null default '#8E1C1C',
  add column if not exists primary_color_light text not null default '#E2574A',
  add column if not exists secondary_color text not null default '#E86A1C',
  add column if not exists accent_color text not null default '#EFA80A',
  add column if not exists accent_color_dark text not null default '#B87F06',
  add column if not exists accent_color_light text not null default '#F7CB63',
  add column if not exists navy_color text not null default '#0B1F3A',
  add column if not exists navy_color_light text not null default '#15335C',
  add column if not exists background_color text not null default '#FFFFFF';

-- ---------- giving_settings (fixes: column "bank_account_name" not found) ----------
alter table public.giving_settings
  add column if not exists message text,
  add column if not exists instructions text,
  add column if not exists mpesa_paybill text,
  add column if not exists mpesa_account text,
  add column if not exists mpesa_till text,
  add column if not exists bank_name text,
  add column if not exists bank_account_name text,
  add column if not exists bank_account_number text,
  add column if not exists bank_branch text;
insert into public.giving_settings (id) values (1) on conflict (id) do nothing;

-- ---------- blog_posts ----------
alter table public.blog_posts
  add column if not exists author text,
  add column if not exists category text,
  add column if not exists excerpt text,
  add column if not exists cover_image text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists focus_keyword text,
  add column if not exists canonical_url text,
  add column if not exists og_title text,
  add column if not exists og_description text,
  add column if not exists og_image text,
  add column if not exists reading_time int,
  add column if not exists published_at timestamptz,
  add column if not exists scheduled_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

-- ---------- live_service_settings ----------
alter table public.live_service_settings
  add column if not exists thumbnail_url text,
  add column if not exists streaming_url text,
  add column if not exists youtube_url text,
  add column if not exists facebook_url text,
  add column if not exists description text;
insert into public.live_service_settings (id) values (1) on conflict (id) do nothing;

-- ---------- prayer_requests: "read" status ----------
alter table public.prayer_requests drop constraint if exists prayer_requests_status_check;
alter table public.prayer_requests add constraint prayer_requests_status_check
  check (status in ('new','read','prayed_for','archived'));

-- ---------- leaders / departments / sermons / events / albums (columns the admin forms write) ----------
alter table public.leaders
  add column if not exists department text,
  add column if not exists facebook_url text,
  add column if not exists instagram_url text;
alter table public.departments
  add column if not exists slug text,
  add column if not exists meeting_day text,
  add column if not exists meeting_time text,
  add column if not exists contact_email text,
  add column if not exists contact_phone text;
alter table public.sermons
  add column if not exists category text,
  add column if not exists video_url text,
  add column if not exists audio_url text,
  add column if not exists youtube_url text,
  add column if not exists thumbnail_url text,
  add column if not exists featured boolean not null default false;
alter table public.events
  add column if not exists end_date date,
  add column if not exists organizer text,
  add column if not exists registration_link text,
  add column if not exists contact_info text,
  add column if not exists featured boolean not null default false;
alter table public.gallery_albums
  add column if not exists category text,
  add column if not exists cover_image text;
alter table public.service_sectors
  add column if not exists contact_phone text,
  add column if not exists meeting text;

notify pgrst, 'reload schema';


-- ===================== 0003_leadership_hierarchy.sql =====================
-- 0003_leadership_hierarchy.sql
-- Adds a tier ("category") to every leader so the public Leadership page can show the structure:
--   1 pastoral_team  2 church_council  3 departmental_heads  4 service_sector_leaders  5 mini_church_leaders
-- Existing leaders are KEPT. They are backfilled once, based on their position/department text.
-- PLEASE REVIEW the backfill result (query at the bottom) and correct any leader in Admin > Leadership.
-- SAFE TO RE-RUN.

alter table public.leaders
  add column if not exists category text,
  add column if not exists phone text,
  add column if not exists email text;

update public.leaders set category = case
  when lower(coalesce("position",'') || ' ' || coalesce(department,'')) like '%pastor%'
    or lower(coalesce("position",'')) like '%bishop%' or lower(coalesce("position",'')) like '%reverend%' then 'pastoral_team'
  when lower(coalesce("position",'') || ' ' || coalesce(department,'')) like '%council%'
    or lower(coalesce("position",'')) like '%elder%' or lower(coalesce("position",'')) like '%trustee%' then 'church_council'
  when lower(coalesce("position",'') || ' ' || coalesce(department,'')) like '%mini church%'
    or lower(coalesce("position",'') || ' ' || coalesce(department,'')) like '%mini-church%'
    or lower(coalesce("position",'') || ' ' || coalesce(department,'')) like '%minichurch%'
    or lower(coalesce("position",'')) like '%group leader%' then 'mini_church_leaders'
  when lower(coalesce("position",'') || ' ' || coalesce(department,'')) like '%sector%'
    or lower(coalesce("position",'')) like '%usher%' or lower(coalesce("position",'')) like '%security%'
    or lower(coalesce("position",'')) like '%media%' then 'service_sector_leaders'
  when lower(coalesce("position",'') || ' ' || coalesce(department,'')) like '%head%'
    or lower(coalesce("position",'')) like '%director%' or lower(coalesce("position",'')) like '%coordinator%' then 'departmental_heads'
  else 'pastoral_team'
end
where category is null;

alter table public.leaders alter column category set default 'pastoral_team';
alter table public.leaders alter column category set not null;

alter table public.leaders drop constraint if exists leaders_category_check;
alter table public.leaders add constraint leaders_category_check
  check (category in ('pastoral_team','church_council','departmental_heads','service_sector_leaders','mini_church_leaders'));

create index if not exists leaders_category_order_idx on public.leaders (category, "order");

notify pgrst, 'reload schema';

-- Review query (run separately):
-- select name, position, department, category from public.leaders order by category, "order";


-- ===================== 0004_mini_church_groups.sql =====================
-- 0004_mini_church_groups.sql
-- A mini-church is a GROUP of members organised under a department. It is not a physical location.
-- This evolves the existing mini_churches table (no parallel table, no data loss):
--   department_id  -> which department the group belongs to (can be changed at any time)
--   group_label    -> optional identifier, e.g. "Group A"
--   meeting_day / meeting_time -> structured schedule (the old free-text "meeting" column is kept)
-- Members and leaders of a group live in the new mini_church_members table.
-- The old "location" column is kept but is no longer required or shown.
-- SAFE TO RE-RUN.

alter table public.mini_churches
  add column if not exists department_id uuid references public.departments(id) on delete set null,
  add column if not exists group_label text,
  add column if not exists meeting_day text,
  add column if not exists meeting_time time;

alter table public.mini_churches alter column location drop not null;

alter table public.mini_churches drop constraint if exists mini_churches_meeting_day_check;
alter table public.mini_churches add constraint mini_churches_meeting_day_check
  check (meeting_day is null or meeting_day in ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'));

create index if not exists mini_churches_department_idx on public.mini_churches (department_id, display_order);

-- Members and leaders of each group
create table if not exists public.mini_church_members (
  id uuid primary key default uuid_generate_v4(),
  mini_church_id uuid not null references public.mini_churches(id) on delete cascade,
  full_name text not null,
  role text not null default 'member' check (role in ('leader','member')),
  phone text,
  display_order int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists mini_church_members_group_idx on public.mini_church_members (mini_church_id, role, display_order);

alter table public.mini_church_members enable row level security;

-- Visitors may see a group's LEADERS only (names of ordinary members stay private)
drop policy if exists "public read mini church leaders" on public.mini_church_members;
create policy "public read mini church leaders" on public.mini_church_members for select
  using (
    is_admin()
    or (role = 'leader' and exists (
      select 1 from public.mini_churches g where g.id = mini_church_id and g.published = true))
  );
drop policy if exists "admins manage mini church members" on public.mini_church_members;
create policy "admins manage mini church members" on public.mini_church_members for all
  using (is_admin()) with check (is_admin());

-- Public member counts without exposing names
create or replace function public.public_mini_church_member_counts()
returns table (mini_church_id uuid, member_count int)
language sql stable security definer set search_path = public as $$
  select m.mini_church_id, count(*)::int
  from public.mini_church_members m
  join public.mini_churches g on g.id = m.mini_church_id
  where g.published = true
  group by m.mini_church_id;
$$;
grant execute on function public.public_mini_church_member_counts() to anon, authenticated;

-- Backfill 1: day/time from the old free-text "meeting" column, e.g. "Sundays · 9:00 AM"
do $$
declare r record; d text; t text[];
begin
  for r in select id, meeting from public.mini_churches where meeting is not null and (meeting_day is null or meeting_time is null) loop
    begin
      d := (regexp_match(r.meeting, '(monday|tuesday|wednesday|thursday|friday|saturday|sunday)', 'i'))[1];
      if d is not null then
        update public.mini_churches set meeting_day = initcap(d) where id = r.id and meeting_day is null;
      end if;
      t := regexp_match(r.meeting, '(\d{1,2}):(\d{2})\s*([ap]m)', 'i');
      if t is not null then
        update public.mini_churches
           set meeting_time = to_timestamp(t[1] || ':' || t[2] || ' ' || upper(t[3]), 'HH12:MI AM')::time
         where id = r.id and meeting_time is null;
      end if;
    exception when others then
      raise notice 'Could not parse meeting text for group %, left unchanged', r.id;
    end;
  end loop;
end $$;

-- Backfill 2: the single "leader_name" becomes a proper leader row (only once)
insert into public.mini_church_members (mini_church_id, full_name, role, phone)
select g.id, g.leader_name, 'leader', g.contact_phone
from public.mini_churches g
where g.leader_name is not null and trim(g.leader_name) <> ''
  and not exists (select 1 from public.mini_church_members m where m.mini_church_id = g.id and m.role = 'leader');

notify pgrst, 'reload schema';


-- ===================== 0005_service_schedule.sql =====================
-- 0005_service_schedule.sql
-- Separates two different things that used to be mixed together:
--   1. NEXT SERVICE  (live_service_settings): the specific upcoming service/event. Either computed
--      automatically from the weekly timetable ("auto") or set to a one-off event ("manual").
--   2. WEEKLY TIMETABLE (service_schedule): the church's regular services. Never changed by the next-service setting.
-- SAFE TO RE-RUN. Seeding only inserts entries that do not already exist.

alter table public.live_service_settings
  add column if not exists next_mode text not null default 'auto',
  add column if not exists service_date date,
  add column if not exists force_live boolean not null default false;

alter table public.live_service_settings drop constraint if exists live_service_next_mode_check;
alter table public.live_service_settings add constraint live_service_next_mode_check
  check (next_mode in ('auto','manual'));
alter table public.live_service_settings drop constraint if exists live_service_manual_needs_date;
alter table public.live_service_settings add constraint live_service_manual_needs_date
  check (next_mode = 'auto' or service_date is not null);

create table if not exists public.service_schedule (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  day_of_week int not null check (day_of_week between 0 and 6),          -- 0 = Sunday ... 6 = Saturday
  start_time time not null,
  end_time time not null,
  recurrence text not null default 'weekly' check (recurrence in ('weekly','monthly_nth')),
  week_of_month int,                                                      -- 1..5, or -1 = last (monthly_nth only)
  timezone text not null default 'Africa/Nairobi',
  is_streamed boolean not null default false,
  stream_url text,
  description text,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_schedule_end_after_start check (end_time > start_time),
  constraint service_schedule_week_valid check (
    (recurrence = 'weekly' and week_of_month is null)
    or (recurrence = 'monthly_nth' and week_of_month is not null and (week_of_month between 1 and 5 or week_of_month = -1))
  )
);

alter table public.service_schedule drop constraint if exists service_schedule_week_valid;
alter table public.service_schedule add constraint service_schedule_week_valid check (
  (recurrence = 'weekly' and week_of_month is null)
  or (recurrence = 'monthly_nth' and week_of_month is not null and (week_of_month between 1 and 5 or week_of_month = -1))
);

create unique index if not exists service_schedule_unique_entry
  on public.service_schedule (name, day_of_week, start_time, coalesce(week_of_month, 0));
create index if not exists service_schedule_day_idx on public.service_schedule (day_of_week, start_time);

alter table public.service_schedule enable row level security;
drop policy if exists "public read active service schedule" on public.service_schedule;
create policy "public read active service schedule" on public.service_schedule for select
  using (is_active = true or is_admin());
drop policy if exists "admins manage service schedule" on public.service_schedule;
create policy "admins manage service schedule" on public.service_schedule for all
  using (is_admin()) with check (is_admin());

-- The church's regular order of services. Overlaps (Wednesday) are intentional and preserved.
insert into public.service_schedule (name, day_of_week, start_time, end_time, recurrence, week_of_month, display_order)
select v.name, v.dow, v.st::time, v.et::time, v.rec, v.wk, v.ord
from (values
  ('Daily Prayers',      1, '18:00', '19:00', 'weekly',      null::int, 10),
  ('Daily Prayers',      2, '18:00', '19:00', 'weekly',      null::int, 11),
  ('Daily Prayers',      3, '18:00', '19:00', 'weekly',      null::int, 12),
  ('Daily Prayers',      4, '18:00', '19:00', 'weekly',      null::int, 13),
  ('Daily Prayers',      5, '18:00', '19:00', 'weekly',      null::int, 14),
  ('Midweek Service',    3, '17:45', '19:30', 'weekly',      null::int, 20),
  ('Youth Service',      0, '08:00', '09:45', 'weekly',      null::int, 30),
  ('Main Service',       0, '10:00', '13:30', 'weekly',      null::int, 40),
  ('Worship Wednesday',  3, '17:45', '20:00', 'monthly_nth', 3,         50)
) as v(name, dow, st, et, rec, wk, ord)
where not exists (
  select 1 from public.service_schedule s
  where s.name = v.name and s.day_of_week = v.dow and s.start_time = v.st::time
    and coalesce(s.week_of_month, 0) = coalesce(v.wk, 0)
);

notify pgrst, 'reload schema';


-- ===================== 0006_integrity_and_policies.sql =====================
-- 0006_integrity_and_policies.sql
-- * Scheduled blog posts become public automatically once their publish time has passed.
-- * updated_at is maintained by the database.
-- * Indexes for the queries the website runs most.
-- SAFE TO RE-RUN.

drop policy if exists "public read published blog_posts" on public.blog_posts;
create policy "public read published blog_posts" on public.blog_posts for select
  using (
    status = 'published'
    or (status = 'scheduled' and scheduled_at is not null and scheduled_at <= now())
    or is_admin()
  );

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_blog_posts_updated on public.blog_posts;
create trigger trg_blog_posts_updated before update on public.blog_posts
  for each row execute function public.set_updated_at();
drop trigger if exists trg_service_schedule_updated on public.service_schedule;
create trigger trg_service_schedule_updated before update on public.service_schedule
  for each row execute function public.set_updated_at();
drop trigger if exists trg_site_settings_updated on public.site_settings;
create trigger trg_site_settings_updated before update on public.site_settings
  for each row execute function public.set_updated_at();

create index if not exists blog_posts_status_published_idx on public.blog_posts (status, published_at desc);
create index if not exists blog_posts_category_idx on public.blog_posts (category);
create index if not exists events_start_date_idx on public.events (start_date);
create index if not exists sermons_date_idx on public.sermons (date desc);
create index if not exists departments_order_idx on public.departments (display_order);
create index if not exists contact_messages_status_idx on public.contact_messages (status, created_at desc);
create index if not exists prayer_requests_status_idx on public.prayer_requests (status, created_at desc);

notify pgrst, 'reload schema';


-- ===================== 0007_storage_policies.sql =====================
-- 0007_storage_policies.sql
-- Upload permissions for the Storage buckets the website can use.
-- The website uploads to the bucket named in VITE_STORAGE_BUCKET (default "church-pics").
-- Public can view files; only administrators (rows in public.profiles) can upload, replace or delete.
-- Buckets are created below if missing ("church-pics" and "media"); a bucket named "church pics"
-- (with a space) is covered by the policies if you created one, but is not created here.
-- SAFE TO RE-RUN.

insert into storage.buckets (id, name, public) values ('church-pics', 'church-pics', true)
  on conflict (id) do update set public = true;
insert into storage.buckets (id, name, public) values ('media', 'media', true)
  on conflict (id) do update set public = true;
update storage.buckets set public = true where id = 'church pics';

drop policy if exists "site media public read" on storage.objects;
create policy "site media public read" on storage.objects for select
  using (bucket_id in ('church-pics', 'church pics', 'media'));

drop policy if exists "site media admin upload" on storage.objects;
create policy "site media admin upload" on storage.objects for insert to authenticated
  with check (bucket_id in ('church-pics', 'church pics', 'media') and public.is_admin());

drop policy if exists "site media admin update" on storage.objects;
create policy "site media admin update" on storage.objects for update to authenticated
  using (bucket_id in ('church-pics', 'church pics', 'media') and public.is_admin());

drop policy if exists "site media admin delete" on storage.objects;
create policy "site media admin delete" on storage.objects for delete to authenticated
  using (bucket_id in ('church-pics', 'church pics', 'media') and public.is_admin());
