-- This file is no longer used.
-- The database is now defined by the numbered files in supabase/migrations (see supabase/README.md).
-- Run those instead: they are safe to run on a database that already exists, and they repair older databases.
